version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-db}",
          "-U",
          "${POSTGRES_USER:-user}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    restart: on-failure
    image: henriquemarlon/notex:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
